process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_wikiqa_exp9_10.json', 'KerasLstmModel_2_trec_exp9_15.json', 'KerasLstmModel_2_trec_exp9_12.json', 'KerasLstmModel_2_trec_exp9_14.json', 'KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_wikiqa_exp9_10.json
data_stats.py: INFO: getStats():  16:	 Questions loaded.
data_stats.py: INFO: getStats():  18:	 Working on train...
data_stats.py: INFO: getStats():  24:	 Questions for train:2117
data_stats.py: INFO: getStats():  24:	 Questions for validate:295
data_stats.py: INFO: getStats():  24:	 Questions for test:632
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset WikiQA !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 20358 samples
PassageRetrieval.py: INFO: run_experiment():  85:	 Testing the model
PassageRetrieval.py: INFO: run_experiment():  100:	 Model performance:, map: 0.5571, mrr: 0.5647
PassageRetrieval.py: INFO: run_experiment():  114:	 End model evaluation, total time: 2728.77979708
process_experiments.py: INFO: start_try():  44:	 end process file KerasLstmModel_2_wikiqa_exp9_10.json
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_15.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet_TrainAll !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 53417 samples
PassageRetrieval.py: INFO: run_experiment():  85:	 Testing the model
PassageRetrieval.py: INFO: run_experiment():  100:	 Model performance:, map: 0.5831, mrr: 0.6529
PassageRetrieval.py: INFO: run_experiment():  114:	 End model evaluation, total time: 905.898224115
process_experiments.py: INFO: start_try():  44:	 end process file KerasLstmModel_2_trec_exp9_15.json
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_12.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet_TrainAll !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 53417 samples
PassageRetrieval.py: INFO: run_experiment():  85:	 Testing the model
PassageRetrieval.py: INFO: run_experiment():  100:	 Model performance:, map: 0.6290, mrr: 0.7003
PassageRetrieval.py: INFO: run_experiment():  114:	 End model evaluation, total time: 2017.44938898
process_experiments.py: INFO: start_try():  44:	 end process file KerasLstmModel_2_trec_exp9_12.json
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_14.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet_TrainAll !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 53417 samples
PassageRetrieval.py: INFO: run_experiment():  85:	 Testing the model
PassageRetrieval.py: INFO: run_experiment():  100:	 Model performance:, map: 0.5762, mrr: 0.6390
PassageRetrieval.py: INFO: run_experiment():  114:	 End model evaluation, total time: 254.925612926
process_experiments.py: INFO: start_try():  44:	 end process file KerasLstmModel_2_trec_exp9_14.json
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: INFO: start_try():  30:	 Experimentation files['KerasLstmModel_2_trec_exp9_11.json', 'KerasLstmModel_2_trec_exp9_1.json']
process_experiments.py: INFO: start_try():  33:	 process model file KerasLstmModel_2_trec_exp9_11.json
PassageRetrieval.py: INFO: run_experiment():  75:	 Loading the dataset TrecDataSet !
PassageRetrieval.py: INFO: run_experiment():  81:	 Loading the model, KerasLstmModel_1
PassageRetrieval.py: INFO: run_experiment():  83:	 Trainning the model
KerasLstmModel_1.py: INFO: train():  97:	 Start Trainning with 4718 samples
process_experiments.py: ERROR: queryRepeatedly():  56:	 Error evaluating model : output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
Traceback (most recent call last):
  File "process_experiments.py", line 54, in queryRepeatedly
    start_try()
  File "process_experiments.py", line 39, in start_try
    report, m_map, m_recip_rank = pr.run_experiment(js, w2v_util, run_id, exp_in_path+exp_file, jshtml)
  File "/home/aerossom/passage-retrieval/PassageRetrieval.py", line 84, in run_experiment
    history = p_model.train(ds, qa_pair)
  File "/home/aerossom/passage-retrieval/KerasLstmModel_1.py", line 114, in train
    callbacks=[checkpoint, earlyStopping],nb_worker=1)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 1417, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
process_experiments.py: ERROR: queryRepeatedly():  57:	 output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
